# Generated by Django 5.2.1 on 2025-05-31 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryMachineDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'fal.ai/flux/dev'", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=150)),
                ('description', models.TextField(help_text='Description of what this machine does')),
                ('provider', models.CharField(help_text="e.g., 'fal.ai', 'replicate'", max_length=50)),
                ('model_family', models.CharField(help_text="e.g., 'flux', 'sdxl', 'stable-diffusion'", max_length=50)),
                ('modality', models.CharField(choices=[('text-to-image', 'Text to Image'), ('image-to-image', 'Image to Image'), ('text-to-video', 'Text to Video'), ('text-to-audio', 'Text to Audio'), ('image-to-video', 'Image to Video')], max_length=20)),
                ('parameter_schema', models.JSONField(default=dict, help_text='JSON schema defining available parameters')),
                ('default_parameters', models.JSONField(default=dict, help_text='Default parameter values')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this machine is available')),
                ('max_concurrent_jobs', models.PositiveIntegerField(default=1, help_text='Max simultaneous operations')),
                ('estimated_duration', models.DurationField(blank=True, help_text='Typical processing time', null=True)),
                ('cost_per_operation', models.DecimalField(blank=True, decimal_places=4, help_text='Estimated cost per generation', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'model_family', 'name'],
                'indexes': [models.Index(fields=['provider'], name='main_factor_provide_53a8e4_idx'), models.Index(fields=['modality'], name='main_factor_modalit_ebc30c_idx'), models.Index(fields=['is_active'], name='main_factor_is_acti_ede036_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional order title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Order description or notes')),
                ('prompt', models.TextField(help_text='Base prompt for generation')),
                ('base_parameters', models.JSONField(default=dict, help_text='Base parameters for all items')),
                ('factory_machine_name', models.CharField(help_text="e.g., 'fal.ai/flux/dev'", max_length=100)),
                ('provider', models.CharField(help_text="e.g., 'fal.ai', 'replicate'", max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of products to generate')),
                ('expand_parameters', models.BooleanField(default=False, help_text='Whether to expand smart tokens')),
                ('project_name', models.CharField(blank=True, help_text='Project organization', max_length=100)),
                ('tags', models.JSONField(default=list, help_text='List of tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='main_order_status_4d3738_idx'), models.Index(fields=['created_at'], name='main_order_created_a818a5_idx'), models.Index(fields=['provider'], name='main_order_provide_377b99_idx'), models.Index(fields=['project_name'], name='main_order_project_cc28d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Processed prompt for this specific item')),
                ('parameters', models.JSONField(default=dict, help_text='Final parameters for generation')),
                ('variation_seed', models.BigIntegerField(blank=True, help_text='Variation seed', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('provider_request_id', models.CharField(blank=True, help_text="Provider's request ID", max_length=200)),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactoryMachineInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(help_text='Unique instance identifier', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('busy', 'Busy'), ('error', 'Error'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='idle', max_length=20)),
                ('current_operation', models.JSONField(blank=True, help_text='Details of current operation if busy', null=True)),
                ('total_operations', models.PositiveIntegerField(default=0)),
                ('successful_operations', models.PositiveIntegerField(default=0)),
                ('failed_operations', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_operation_at', models.DateTimeField(blank=True, null=True)),
                ('machine_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.factorymachinedefinition')),
                ('current_order_item', models.ForeignKey(blank=True, help_text='Currently processing order item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.orderitem')),
            ],
            options={
                'ordering': ['machine_definition', 'instance_id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_format', models.CharField(help_text="e.g., 'jpg', 'png', 'mp4'", max_length=20)),
                ('product_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='image', max_length=10)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, help_text='For video/audio', null=True)),
                ('prompt', models.TextField(help_text='The prompt used to generate this product')),
                ('parameters', models.JSONField(default=dict, help_text='Full generation parameters as JSON')),
                ('seed', models.BigIntegerField(blank=True, help_text='Random seed used', null=True)),
                ('provider', models.CharField(help_text="e.g., 'fal.ai', 'replicate'", max_length=50)),
                ('model_name', models.CharField(help_text="e.g., 'flux/dev', 'sdxl'", max_length=100)),
                ('provider_id', models.CharField(blank=True, help_text="Provider's internal ID", max_length=200)),
                ('tags', models.JSONField(default=list, help_text='List of tags for organization')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='main_produc_created_276cd8_idx'), models.Index(fields=['product_type'], name='main_produc_product_282233_idx'), models.Index(fields=['provider'], name='main_produc_provide_4d16ee_idx'), models.Index(fields=['is_favorite'], name='main_produc_is_favo_2f8079_idx')],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('logger_name', models.CharField(help_text='Name of the logger', max_length=100)),
                ('module', models.CharField(blank=True, help_text='Python module name', max_length=100)),
                ('function', models.CharField(blank=True, help_text='Function name', max_length=100)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(default=dict, help_text='Additional log context')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.factorymachineinstance')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.orderitem')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level'], name='main_logent_level_6c7921_idx'), models.Index(fields=['timestamp'], name='main_logent_timesta_dc43ff_idx'), models.Index(fields=['logger_name'], name='main_logent_logger__822527_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='factorymachineinstance',
            index=models.Index(fields=['status'], name='main_factor_status_4116fc_idx'),
        ),
        migrations.AddIndex(
            model_name='factorymachineinstance',
            index=models.Index(fields=['machine_definition', 'status'], name='main_factor_machine_d28ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['status'], name='main_orderi_status_307ded_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'status'], name='main_orderi_order_i_c01045_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['provider_request_id'], name='main_orderi_provide_9b488c_idx'),
        ),
    ]
