# Generated by Django 5.2.1 on 2025-06-01 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Worker'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('stalled', 'Stalled - Manual Retry Required'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique worker name', max_length=100)),
                ('process_id', models.IntegerField(help_text='OS process ID', unique=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('working', 'Working'), ('exiting', 'Exiting')], default='starting', max_length=20)),
                ('provider', models.CharField(help_text='Provider this worker handles (fal.ai, replicate)', max_length=50)),
                ('max_batch_size', models.IntegerField(default=5, help_text='Maximum items to process in one batch')),
                ('spawned_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('extra_data', models.JSONField(default=dict, help_text='Additional worker context')),
            ],
            options={
                'ordering': ['-spawned_at'],
                'indexes': [models.Index(fields=['status'], name='main_worker_status_172d53_idx'), models.Index(fields=['provider'], name='main_worker_provide_9aaac2_idx'), models.Index(fields=['process_id'], name='main_worker_process_5dc682_idx'), models.Index(fields=['last_heartbeat'], name='main_worker_last_he_7b24d7_idx')],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.worker'),
        ),
    ]
