# Generated by Django 5.2.1 on 2025-06-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_batch_generation_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last retry attempt', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Maximum retry attempts for transient failures'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of retry attempts'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Worker'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('exhausted', 'Failed - Max Retries Exhausted'), ('stalled', 'Stalled - Manual Retry Required'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
