# Generated by Django 5.2.1 on 2025-06-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_retry_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='negative_prompt',
            field=models.TextField(blank=True, default='', help_text='What to avoid in the generated image'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='negative_prompt',
            field=models.TextField(blank=True, default='', help_text='What to avoid in the generated image'),
        ),
        migrations.AddField(
            model_name='product',
            name='negative_prompt',
            field=models.TextField(blank=True, default='', help_text='What to avoid in the generated image'),
        ),
    ]
