# Generated by Django 5.2.1 on 2025-06-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_add_partially_completed_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="error_category",
            field=models.CharField(blank=True, help_text="Error category for retry logic", max_length=50),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="error_message",
            field=models.TextField(blank=True, help_text="User-friendly error message"),
        ),
    ]
