# Generated by Django 5.2.1 on 2025-06-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_orderitem_error_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="project_name",
            field=models.CharField(blank=True, help_text="Legacy project name field", max_length=100),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Project name", max_length=200)),
                ("description", models.TextField(blank=True, help_text="Project description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived"), ("completed", "Completed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "product_count",
                    models.PositiveIntegerField(default=0, help_text="Total number of products in this project"),
                ),
                ("order_count", models.PositiveIntegerField(default=0, help_text="Total number of orders in this project")),
                (
                    "featured_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Featured products to display on project overview",
                        related_name="featured_in_projects",
                        to="main.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.project",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["project"], name="main_order_project_37a438_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="main_projec_status_10c85e_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["created_at"], name="main_projec_created_0bbe51_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["-updated_at"], name="main_projec_updated_7ad2dc_idx"),
        ),
    ]
